cmake_minimum_required(VERSION 3.16)

project(NDSLocUtils
    VERSION 1.0.0
    LANGUAGES CXX
)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(PROJECT_NAME_CORE ${PROJECT_NAME}Core)
set(PROJECT_NAME_GUI ${PROJECT_NAME}Gui)

add_subdirectory(src/core)
add_subdirectory(src/ui)

set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    PROPERTY VS_STARTUP_PROJECT ${PROJECT_NAME_GUI}
)
